config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  root 'breweries#index'
  get 'ratings', to: 'ratings#index'
  get 'ratings/new', to: 'ratings#new'
  post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :destroy]

  resources :memberships, only: [:new, :create]
  
  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  resources :styles

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    member do
      post :close_account
      post :open_account
    end
  end

end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :beer_club
  belongs_to :user
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, only: [:new, :create, :destroy]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @available_beer_clubs = BeerClub.all - current_user.beer_clubs
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @membership.user = current_user

    respond_to do |format|
      if @membership.save
        format.html { redirect_to beer_club_path(@membership.beer_club), notice: "#{current_user.username} welcome to the club!" }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    if @membership.update(membership_params)
      redirect_to @membership, notice: 'Membership was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @membership = Membership.find(params[:id])
    beer_club = @membership.beer_club
    if current_user == @membership.user
      @membership.destroy
      redirect_to user_path(current_user), notice: 'Membership was successfully destroyed.'
    else
      redirect_to beer_club, alert: 'Only membership owner can destroy membership'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def membership_params
    params.require(:membership).permit(:beer_club_id, :user_id, :id)
  end

  def ensure_that_signed_in
    redirect_to signin_path, alert: 'You must be signed in' unless current_user
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :beer_club_id, style: "display: block" %>
    <%= form.text_field :beer_club_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Beer club:</strong>
    <%= membership.beer_club_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= membership.user_id %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<h1>Join a Beer Club</h1>

<% @available_beer_clubs.each do |club| %>
  <%= form_with(model: Membership.new, url: memberships_path, method: :post) do |form| %>
    <div>
      <%= club.name %>
      <%= form.hidden_field :beer_club_id, value: club.id %>
      <%= form.submit "Join" %>
    </div>
  <% end %>
<% end %>

<div>
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/show.html.erb
<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete %>
</div>