config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  root 'breweries#index'
  get 'ratings', to: 'ratings#index'
  get 'ratings/new', to: 'ratings#new'
  post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :destroy]

  resources :memberships, only: [:new, :create]
  
  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  resources :styles

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    member do
      post :close_account
      post :open_account
    end
  end

end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :members, through: :memberships, source: :user
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_admin, only: [:destroy]
  before_action :set_beer_club, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @beer_club = BeerClub.find(params[:id])

    return unless current_user

    @membership = current_user.memberships.find_by(beer_club: @beer_club)
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end

  def ensure_that_admin
    redirect_to breweries_path, notice: 'Only admins can do that' unless current_user.admin?
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <p>
    <strong>Name:</strong>
    <%= beer_club.name %>
  </p>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>
</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please provide a name for the beer club.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :founded, class: 'form-label' %>
    <%= form.number_field :founded, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please provide a founding year.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :city, class: 'form-label' %>
    <%= form.text_field :city, class: 'form-control', required: true %>
    <div class="invalid-feedback">
      Please provide a city.
    </div>
  </div>


  <div>
    <%= form.submit "Create Beer Club", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<div id="beer_clubs">
  <% @beer_clubs.each do |beer_club| %>
    <%= render beer_club %>
    <p>
      <%= link_to "Show this beer club", beer_club %>
    </p>
  <% end %>
</div>


<%= link_to("New beer club", new_beer_club_path) if current_user %> 

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<strong>Jäsenet:</strong>
<ul>
  <% @beer_club.members.each do |member| %>
    <li><%= link_to member.username, user_path(member) %></li>
  <% end %>
</ul>

<% if current_user %>
  <% membership = @beer_club.memberships.find_by(user: current_user) %>
  <% if membership %>
    <%= form_with(model: membership, url: membership_path(membership), method: :delete) do |form| %>
      <%= form.submit "End the membership" %>
    <% end %>
  <% else %>
    <%= form_with(model: Membership.new, url: memberships_path, method: :post) do |form| %>
      <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
      <%= form.submit "Join the club" %>
    <% end %>
  <% end %>
<% end %>


<div>
<%= edit_and_destroy_buttons(@beer_club) %>
    <% if current_user&.admin? %>
      <%= button_to "Destroy this beer_club", @beer_club, method: :delete, class: "btn btn-danger"  %>
    <% end %>
</div>