config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  root 'breweries#index'
  get 'ratings', to: 'ratings#index'
  get 'ratings/new', to: 'ratings#new'
  post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :destroy]

  resources :memberships, only: [:new, :create]
  
  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  resources :styles

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    member do
      post :close_account
      post :open_account
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage

  has_secure_password validations: false

  validates :username, uniqueness: true,
                       length: { minimum: 3, maximum: 30 }

  validates :password, length: { minimum: 4 },
                       format: { with: /(?=.*[A-Z])(?=.*\d)/,
                                 message: 'should have at least one uppercase letter and one digit' }

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships

  def self.top(num)
    User.all.max_by(num) { |user| user.ratings.count }
  end

  def favorite_style
    return nil if ratings.empty?

    style_ratings = ratings.joins(beer: :style).group('styles.name').average('ratings.score')
    style_ratings.max_by { |_style, avg_rating| avg_rating }&.first
  end

  def favorite_brewery
    return nil if ratings.empty?

    brewery_ratings = ratings.joins(beer: :brewery).group('breweries.name').average(:score)
    best_brewery_name = brewery_ratings.max_by { |_name, avg_rating| avg_rating }[0]

    Brewery.find_by(name: best_brewery_name)
  end

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).first.beer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if current_user == User.find(params[:id])
      respond_to do |format|
        if user_params[:username].nil? && @user == current_user && @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: "You cannot edit another user's details!"
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if current_user == User.find(params[:id])
      current_user.destroy
      session[:user_id] = nil # log out
      redirect_to root_path, notice: 'Your account has been deleted.'
    else
      redirect_to root_path, notice: 'You cannot delete another user\'s account!'
    end
  end

  def close_account
    @user = User.find(params[:id])
    if current_user.admin?
      @user.update_column(:account_closed, true)
      redirect_to users_path, notice: "Account has been closed."
    else
      redirect_to users_path, alert: "You are not authorized to perform this action."
    end
  end

  def open_account
    @user = User.find(params[:id])
    if current_user.admin?
      @user.update_column(:account_closed, false)
      redirect_to users_path, notice: "Account has been opened."
    else
      redirect_to users_path, alert: "You are not authorized to perform this action."
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div>
      <%= form.label :username, style: "display: block" %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div>
    <%= form.label :password, style: "display: block"%>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block"%>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <h3>Username:</h3>
    <%= user.username %>
  </p>
</div>

app/views/users/edit.html.erb
<% unless @user.new_record? %>
  <h1>Change password for user <%= @user.username %></h1>
<% end %>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users" class="list-group">
  <% @users.each do |user| %>
    <div class="list-group-item">
      <%= render user %>
      <p class="mt-2">
        <%= link_to "Show this user", user, class: 'btn btn-outline-primary' %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<%= render @user %>

<% if current_user && current_user.admin? %>
  <% if @user.account_closed? %>
    <%= button_to "Open account", open_account_user_path(@user), data: { turbo_method: :post, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% else %>
    <%= button_to "Close account", close_account_user_path(@user), data: { turbo_method: :post, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% end %>
<% end %>



<p>Favorite Style: <%= @user.favorite_style %></p>

<% if @user.favorite_brewery %>
  <p>Favorite Brewery: <%= @user.favorite_brewery.name %></p>
<% else %>
  <p>No favorite brewery yet.</p>
<% end %>

<h3>Member of</h3>
<ul>
  <% @user.beer_clubs.each do |club| %>
    <li><%= link_to club.name, beer_club_path(club) %></li>
  <% end %>
</ul>


<p>
  Has made <%= @user.ratings.count %> rating, average rating <%= @user.average_rating %>
</p>

<h3>ratings:</h3>
<ul>
  <% @user.ratings.each do |rating| %>
    <li><%= "#{rating.to_s}" %>
      <% if @user == current_user %>
        <%= link_to "Delete", rating, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "delete-rating-link" %>

      <% end %>
    </li>
  <% end %>
</ul>


<div>
  <% if @user == current_user %>
    <%= link_to "Edit this user", edit_user_path(@user) %> |
  <% end %>
  <%= link_to "Back to users", users_path %>

  <% if @user == current_user %>
    <%= button_to "Destroy this user", @user, method: :delete %>
  <% end %>
</div>